### ISSUE TITLE
Staging ETH bounty test pre-launch #1

### ISSUE THREAD

**Issue by lmyslinski** [PRHunter-io/sandbox#38]

**Comment by ghost** [comment]
A new [PRHunter bounty](http://localhost:3000/bounties/f38a36af-df05-460d-90a4-4e9615472205) was just created for this issue! The author offers 0.01 ETH (~$24.5621) for solving it. Submit a pull request to claim your reward. More details [here](http://localhost:3000/docs#completing-bounties).

**Comment by ghost** [comment]
A new [PRHunter bounty](https://staging.prhunter.io/bounties/7db885f3-58ff-471c-a62c-797d5dfd4bb0) was just created for this issue! The author offers 0.028 BNB (~$10.52492) for solving it. Submit a pull request to claim your reward. More details [here](https://staging.prhunter.io/docs#completing-bounties).

**Comment by ghost** [comment]
A new [PRHunter bounty](http://localhost:3000/bounties/44203a37-0243-417e-a37b-a6c6d111db11) was just created for this issue! The author offers 0.248 BNB (~$101.85608) for solving it. Submit a pull request to claim your reward. More details [here](http://localhost:3000/docs#completing-bounties).
