### ISSUE TITLE
Localtest #1

### ISSUE THREAD

**Issue by lmyslinski** [PRHunter-io/sandbox#40]

**Comment by ghost** [comment]
A new [PRHunter bounty](http://localhost:3000/bounties/120f75c0-6575-455f-9bf1-222a7d6e8566) was just created for this issue! The author offers 0.018000000000000002 BNB (~$6.73272000000000074808) for solving it. Submit a pull request to claim your reward. More details [here](http://localhost:3000/docs#completing-bounties).

**Comment by ghost** [comment]
A new [PRHunter bounty](http://localhost:3000/bounties/b7b1d1d8-b3df-4bb4-a53d-169240431657) was just created for this issue! The author offers 0.118 ETH (~$343.84610) for solving it. Submit a pull request to claim your reward. More details [here](http://localhost:3000/docs#completing-bounties).
